[workspace]
release = false

[[package]]
name = "crates/minijinja-lua"
publish_features = ["vendored", "contrib"]

[[package]]
name = "crates/rsjson-lua"
publish_features = ["vendored"]

[[package]]
name = "crates/rsre-lua"
publish_features = ["vendored"]
