cargo-features = ["panic-immediate-abort", "profile-rustflags"]

[workspace]
resolver = "3"
members = [
  "crates/minijinja-lua",
  "crates/rs-mod-lua-core",
  "crates/rsast-lua",
  "crates/rsjson-lua",
  "crates/rsre-lua",
]

[workspace.package]
edition = "2024"
repository = "https://github.com/benniekiss/rs-mod-lua"
license = "MIT"

[workspace.dependencies]
mlua = { version = "0.12.2", default-features = false }
rs-mod-lua-core = { path = "crates/rs-mod-lua-core", version = "0.1.2", default-features = false }

[profile.release]
opt-level = 3
strip = true
lto = true
panic = "unwind"
codegen-units = 1
rustflags = [
  "-Dwarnings",
  "-Zlocation-detail=none",
  "-Zfmt-debug=none",
]
