package = "rsre-lua"
version = "0.2.6"
lua = ">=5.1"

[description]
summary = "a regex lua module using the fancy-regex rust crate"
homepage = "https://github.com/benniekiss/rsre-lua"
issues_url = "https://github.com/benniekiss/rsre-lua/issues"
maintainer = "benniekiss"
labels = ["regex"]
license = "MIT"

[source]
url = "https://github.com/benniekiss/rs-mod-lua/archive/refs/tags/$(PACKAGE)-v$(VERSION).zip"
dev = "git+https://github.com/benniekiss/rs-mod-lua"
dir = "rs-mod-lua-$(PACKAGE)-v$(VERSION)/crates/$(PACKAGE)"

[build]
type = "rust-mlua"
default_features = false
features = ["module"]

[build.modules]
"rsre" = "rsre_lua"

[build.include]
"library/rsre.d.lua" = "rsre.d.lua"

[test]
type = "busted"
