package = "rsjson-lua"
version = "0.6.0"
lua = ">=5.1"

[description]
summary = "a json lua module using the serde-json rust crate"
maintainer = "benniekiss"
homepage = "https://github.com/benniekiss/rs-mod-lua"
issues_url = "https://github.com/benniekiss/rs-mod-lua/issues"
labels = ["json", "rust", "bindings"]
license = "MIT"

[source]
url = "https://github.com/benniekiss/rs-mod-lua/archive/refs/tags/$(PACKAGE)-v$(VERSION).zip"
dev = "git+https://github.com/benniekiss/rs-mod-lua"
dir = "rs-mod-lua-$(PACKAGE)-v$(VERSION)/crates/$(PACKAGE)"

[build]
type = "rust-mlua"
default_features = false
features = ["module"]

[build.modules]
"rsjson" = "rsjson_lua"

[build.include]
"library/rsjson.d.lua" = "rsjson.d.lua"

[test]
type = "busted"

# [test_dependencies]
# rapidjson = "0.7.2-1"
# dkjson = "2.10-1"
# luamark = "1.1.2-1"
# lua-cjson = "2.1.0-1"
# lpeg = "1.1.0-2"
