package = "rsjson-lua"
lua = ">=5.1"

[description]
summary = "a json library for lua using serde-json"
maintainer = "benniekiss"
homepage = "https://github.com/benniekiss/rsjson-lua"
issues_url = "https://github.com/benniekiss/rsjson-lua/issues"
labels = ["json", "rust", "bindings"]
license = "MIT"

[source]
url = "https://github.com/benniekiss/rs-mod-lua/archive/refs/tags/$(PACKAGE)-$(REF).zip"
dev = "git+https://github.com/benniekiss/rs-mod-lua"
tag = "$(REF)"
dir = "crates/rsjson-lua"

[build]
type = "rust-mlua"
default_features = false
features = ["module"]

[build.modules]
"rsjson_lua" = "rsjson_lua"

[build.include]
"lua/rsjson.lua" = "rsjson.lua"

[test]
type = "busted"
