local jsonschema = require("jsonschema")

describe("uri#jsonschema", function ()
    it("exposes parsed URI components#uri", function ()
        local uri = jsonschema.Uri.parse("https://example.com/schema?version=1#/$defs/count")
        assert.is_userdata(uri)
        assert.Equal("https://example.com/schema?version=1#/$defs/count", tostring(uri))
        assert.Equal("https", uri.scheme)
        assert.Equal("example.com", uri.authority)
        assert.Equal("/schema", uri.path)
        assert.Equal("version=1", uri.query)
        assert.Equal("/$defs/count", uri.fragment)
        assert.True(uri:has_authority())
        assert.True(uri:has_query())
        assert.True(uri:has_fragment())
    end)

    it("returns nil for absent components#uri", function ()
        local uri = jsonschema.Uri.parse("urn:example:schema")
        assert.Nil(uri.authority)
        assert.Nil(uri.query)
        assert.Nil(uri.fragment)
        assert.False(uri:has_authority())
        assert.False(uri:has_query())
        assert.False(uri:has_fragment())
    end)

    it("returns URI userdata from transformations#uri", function ()
        local uri = jsonschema.Uri.parse("https://EXAMPLE.com/schema#count")
        local normalized = uri:normalize()
        assert.is_userdata(normalized)
        assert.Equal("https://example.com/schema#count", tostring(normalized))
        assert.Equal("https://EXAMPLE.com/schema", tostring(uri:strip_fragment()))
        assert.Equal("count", uri.fragment)
        uri:set_fragment("other")
        assert.Equal("other", uri.fragment)
        uri:set_fragment(nil)
        assert.Nil(uri.fragment)
        assert.False(uri:has_fragment())
    end)

    it("raises a Lua error for invalid URIs#uri", function ()
        assert.has_error(function () jsonschema.Uri.parse("https://exa mple.com") end)
    end)
end)
