cargo-features = ["panic-immediate-abort", "profile-rustflags"]

[package]
name = "rsast-lua"
version = "0.4.0"
edition = "2024"
description = "a PEG lua module using the pest rust crate"
repository = "https://github.com/benniekiss/rs-mod-lua"
license = "MIT"
keywords = ["lua", "mlua", "module", "parsing", "pest"]
categories = ["parsing"]

[lib]
crate-type = ["cdylib", "rlib"]
name = "rsast_lua"

[dependencies]
mlua = { workspace = true, features = ["macros", "serde"] }
pest = { version = "2.9.1", features = ["miette-error", "pretty-print"] }
pest_meta = { version = "2.9.1", features = ["grammar-extras"] }
pest_vm = { version = "2.9.1", features = ["grammar-extras"] }
serde = { version = "1.0.229", features = ["derive", "rc"] }

[dev-dependencies]
pest_derive = "2.9.1"

[features]
default = ["lua54", "vendored"]
lua51 = ["mlua/lua51"]
lua52 = ["mlua/lua52"]
lua53 = ["mlua/lua53"]
lua54 = ["mlua/lua54"]
lua55 = ["mlua/lua55"]
luajit = ["mlua/luajit"]
luajit52 = ["mlua/luajit52"]
module = ["mlua/module"]
vendored = ["mlua/vendored"]
