package = "rsast-lua"
version = "0.1.2"
lua = ">=5.1"

[description]
summary = "a PEG lua module using the pest rust crate"
maintainer = "benniekiss"
homepage = "https://github.com/benniekiss/rs-mod-lua"
issues_url = "https://github.com/benniekiss/rs-mod-lua/issues"
labels = ["ast", "PEG", "parsing", "rust"]
license = "MIT"

[source]
url = "https://github.com/benniekiss/rs-mod-lua/archive/refs/tags/$(PACKAGE)-v$(VERSION).zip"
dev = "git+https://github.com/benniekiss/rs-mod-lua"
dir = "rs-mod-lua-$(PACKAGE)-v$(VERSION)/crates/$(PACKAGE)"

[build]
type = "rust-mlua"
default_features = false
features = ["module"]

[build.modules]
"rsast" = "rsast_lua"

[build.include]
"library/rsast.d.lua" = "rsast.d.lua"

[test]
type = "busted"

# [test_dependencies]
# luamark = "1.1.2-1"
# lpeg = "1.1.0-2"
# rsjson-lua = "0.6.1"
# luasocket = "3.1.0-1"
