cargo-features = ["panic-immediate-abort", "profile-rustflags"]

[package]
name = "minijinja-lua"
version = "0.5.0"
edition = "2024"
description = "a minijinja lua module using the minijinja rust crate"
repository = "https://github.com/benniekiss/rs-mod-lua"
license = "MIT"
keywords = ["lua", "minijinja", "mlua", "module", "templating"]
categories = ["template-engine"]

[lib]
crate-type = ["cdylib", "rlib"]
name = "minijinja_lua"

[dependencies]
jiff = { version = "0.2.35", features = ["serde"], optional = true }
minijinja = {
  version = "2.24.0",
  features = [
    "custom_syntax",
    "fuel",
    "json",
    "loop_controls",
    "preserve_order",
    "speedups",
    "stacker",
    "unicode",
    "urlencode",
  ]
}
minijinja-contrib = {
  version = "2.24.0",
  features = [
    "datetime",
    "html_entities",
    "pycompat",
    "rand",
    "unicode_wordwrap",
    "wordcount",
  ],
  optional = true
}
mlua = { workspace = true, features = ["macros", "serde"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = {
  version = "1.0.151",
  features = [
    "float_roundtrip",
    "preserve_order",
  ],
  optional = true
}

[features]
default = ["contrib", "lua54", "vendored"]
contrib = ["datetime", "json", "minijinja-contrib"]
datetime = ["dep:jiff"]
json = ["dep:serde_json"]
lua51 = ["mlua/lua51"]
lua52 = ["mlua/lua52"]
lua53 = ["mlua/lua53"]
lua54 = ["mlua/lua54"]
lua55 = ["mlua/lua55"]
luajit = ["mlua/luajit"]
luajit52 = ["mlua/luajit52"]
minijinja-contrib = ["dep:minijinja-contrib"]
module = ["mlua/module"]
vendored = ["mlua/vendored"]
