name: Prek

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  lua-version:
    if: github.head_ref == '' || !startsWith(github.head_ref, 'release-plz-')
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - id: version
        run: |
          echo "version=$(cat .lua-version)" >> "$GITHUB_OUTPUT"

  prek:
    # Do not run on release-plz PRs
    if: github.head_ref == '' || !startsWith(github.head_ref, 'release-plz-')
    runs-on: ubuntu-latest
    needs: lua-version

    env:
      LUA_VERSION: ${{needs.lua-version.outputs.version}}

    steps:
      - name: install readline headers
        run: sudo apt-get -y update && sudo apt-get -y install libreadline-dev

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Lux
        uses: lumen-oss/gh-actions-lux@d12a6bdf3a380de5b9d142272e6fd95d28b44b8d # v1
        with:
          version: ${{ vars.LUX_VERSION }}

      - name: Sync project
        run: |
          lx --no-luarc --lua-version ${{ env.LUA_VERSION }} sync

      - name: Run prek
        uses: j178/prek-action@5337cb91e0fa35a7ff31b9ca345126d8bbbcdf16 # v2
